export const lightColors = {
    primary: "#007AFF",
    primaryVariant: "#0062CC",
    secondary: "#5856D6",
    background: "#F2F2F7",
    backgroundSecondary: "#FFFFFF",
    favIconInactive: "#A1A1AA",
    textPrimary: "#121212",
    textSecondary: "#555555",
    textLight: "#8F8F8F",
    offer1Background: "#5856D6",
    error: "#FF3B30",
    white: "#FFFFFF",
    black: "#000000",
    success: "#34C759",
    sale: "#FF3B30",
    new: "#007AFF",
    featured: "#5856D6",
    default: "#E3E3E3",
    bottomNavMenuBackground: "#007AFF",
    bottomNavigationBackground: "#FFFFFF",
    bottomNavigationActiveTint: "#007AFF",
    searchIconBackground: "#F5F5F5",
    bottomNavActiveLabel: "#ffffff",
    bottomNavInactiveLabel: "#B2B2B2",
    menuButton: "#1A1A1A",
};

export const darkColors = {
    primary: "#0A84FF",
    primaryVariant: "#409CFF",
    secondary: "#5E5CE6",
    background: "#1C1C1E",
    backgroundSecondary: "#2C2C2E",
    favIconInactive: "#8E8E93",
    textPrimary: "#FFFFFF",
    textSecondary: "#AEAEB2",
    offer1Background: "#5E5CE6",
    error: "#FF453A",
    white: "#FFFFFF",
    textLight: "#8E8E93",
    black: "#000000",
    success: "#30D158",
    sale: "#FF453A",
    new: "#0A84FF",
    featured: "#5E5CE6",
    bottomNavMenuBackground: "#ffffff",
    bottomNavigationBackground: "#2C2C2E",
    bottomNavigationActiveTint: "#0A84FF",
    searchIconBackground: "#3A3A3C",
    bottomNavActiveLabel: "#FFFFFF",
    bottomNavInactiveLabel: "#8E8E93",
    menuButton: "#ffffff",
}; 

export type ColorTheme = typeof lightColors;